### ISSUE TITLE
window execute code

### ISSUE THREAD

**Issue by lluiscab** [TamkeenLMS/electron-window-manager#30]
Can the window.execute method run a function instead of sending the code to be executed as a string? window.execute(function() { test(); }) instead of window.execute('test();')

**Comment by TamkeenLMS** [comment]
Probably no. Electron will take the JS code as a string and evaluate it on the render process for the targeted window/html. Passing the code this way wont work because the scope of the code would be the one of the your js code, not the one inside the targeted window. You can read more about this on the official Electron docs.
